name: C++ Build

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest  

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up MinGW
      shell: cmd
      run: |
        choco install mingw -y
        set PATH=%PATH%;C:\ProgramData\chocolatey\bin
        set PATH=%PATH%;C:\Program Files\mingw-w64\{your-version}\bin  

    - name: Build the project
      shell: pwsh
      run: |
        cd ${{ github.workspace }}
        mingw32-make -f makefile

    - name: Upload bin folder as artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: battle-network-bin
        path: ./bin

    - name: Create a GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.date.outputs.tag }}
        files: ./bin/**
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
