name: Build and Release Linux

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up environment
      run: sudo apt-get install -y build-essential pkg-config libsdl2-dev libsdl2-mixer-dev libsdl2-image-dev libsdl2-ttf-dev

    - name: Get version from file
      id: get_version
      run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

    - name: Build project
      run: make -f makefile-linux

    - name: Archive bin directory
      run: |
        zip -r release-linux-${{ env.VERSION }}.zip ./bin
      shell: bash

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./release-linux-${{ env.VERSION }}.zip
        tag_name: v${{ env.VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
